--Tabela cliente
create table if not exists CLIENTE(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
TELEFONE VARCHAR(20) NOT NULL UNIQUE,
DATA_CADASTRO DATE NOT NULL
);

--Tabela serviços
CREATE TABLE IF NOT EXISTS SERVICOS(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DESCRICAO TEXT NOT NULL,
PRECO NUMERIC (10,2) NOT NULL CHECK  (PRECO > 0),
TIPO_SERVICO VARCHAR(50) NOT NULL CHECK (TIPO_SERVICO IN ('Consotoria', 'Suporte', 'Manutenção'))
);

--tabela tecnico
CREATE TABLE IF NOT EXISTS TECNICO(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
ESPECIALIDADE VARCHAR(50) NOT NULL,
DATA_CONTRARACAO DATE NOT NULL
);

--Tabela chamados
CREATE TABLE IF NOT EXISTS CHAMADOS(
ID SERIAL PRIMARY KEY,
CLIENTE_ID INT,
TECNICO_ID INT,
SERVICO_ID INT,
DATA_CHAMADO DATE NOT NULL,
STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Pendente', 'Em andamento', 'Finalizado')) NOT NULL,
DESCRICAO TEXT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
CONSTRAINT FK_TECNICO FOREIGN KEY (TECNICO_ID) REFERENCES TECNICO(ID) ON DELETE CASCADE,
CONSTRAINT FK_SERVICO FOREIGN KEY (SERVICO_ID) REFERENCES SERVICOS(ID) ON DELETE CASCADE
);

--TABELA PAGAMENTOS
CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID SERIAL PRIMARY KEY,
CLIENTE_ID INT,
CHAMADOS_ID INT,
VALOR_PAGO NUMERIC (10,2) NOT NULL CHECK (VALOR_PAGO > 0),
DATA_PAGAMENTO DATE NOT NULL,
FORMA_DE_PAGAMENTO VARCHAR(50) NOT NULL,
CONSTRAINT FK_CLIENTE_PAGAMENTO FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
CONSTRAINT FK_CHAMADOS FOREIGN KEY (CHAMADOS_ID) REFERENCES CHAMADOS(ID) ON DELETE CASCADE
);

--Tabela inserts
INSERT INTO CLIENTE(NOME, EMAIL, TELEFONE, DATA_CADASTRO)
VALUES('João Silva', 'joao@email.com', '(11) 98765-4321', '2023-01-15'),
('Maria Oliveira', 'maria@email.com', '(31) 99654- 3210', '2023-02-20'),
('Pedro Souza', 'pedro@email.com', '(31) 99765- 1234', '2023-03-10'),
('Ana Costa', 'ana@email.com', '(41) 98888-9999', '2023-04-25'),
('Lucas almeida', 'lucas@email.com', '(61) 99123-4567', '2023-05-30');

INSERT INTO SERVICOS(NOME, DESCRICAO, PRECO, TIPO_SERVICO)
VALUES('Consultoria em TI', 'Consultoria especializada em infraestrutura de TI', '500.00', 'Consultoria'),
('Manutenção de Equipamentos', 'Manutenção preventiva e corretiva de equipamentos', '300.00', 'Manutenção'),
('Suporte Técnico', 'Suporte remoto e presencial para empresas', '200.00', 'Suporte');

INSERT INTO TECNICO(NOME, ESPECIALIDADE, DATA_CONTRARACAO)
VALUES('Carlos Oliveira', 'Consultoria TI', '2022-10-10'),
('Fernanda Souza', 'Manutenção', '2021-06-15' ),
('Roberto Costa', 'Suporte Técnico', '2020-08-20');

INSERT INTO CHAMADOS(CLIENTE_ID, TECNICO_ID, SERVICO_ID, DATA_CHAMADO, STATUS, DESCRICAO)
VALUES(4, 1, 1, '2023-06-01', 'Pendente', 'Fiação da casa queimada'),
(5, 2, 2, '2023-07-10', 'Em andamento', 'Vazamento na tubulação'),
(6, 3, 3, '2023-08-05', 'Finalizado', 'Reparação no ar-condicionado'),
(7, 1, 2, '2023-09-20', 'Pendente', 'Manutenção no servidor'),
(8, 2, 1, '2023-10-15', 'Finalizado', 'Suporte para software');

INSERT INTO PAGAMENTOS(CLIENTE_ID, CHAMADOS_ID, VALOR_PAGO, DATA_PAGAMENTO, FORMA_DE_PAGAMENTO)
VALUES(4, 7, '350.00', '2023-06-15' , 'Cartão de Crédito'),
(5, 8, '450.00', '2023-07-15','Cartão de Crédito'),
(6, 9, '600.00', '2023-08-10', 'Cartão de Crédito'),
(7, 10, '300.00', '2023-09-25', 'Cartão de Crédito');

SELECT * FROM CLIENTE
SELECT * FROM SERVICOS
SELECT * FROM TECNICO
SELECT * FROM CHAMADOS
SELECT * FROM PAGAMENTOS